### ISSUE TITLE
Test con falla

### ISSUE THREAD

**Issue by NSci** [NSci/PdP-TP-Objetos#14]
@gonziesc  este es el test que sigue fallando.

Dice que encuentra el mismo set que esta esperando, pero tira error.
Aveces dice que encuentra el set alreves (primero almaDeDiamante y despues crisantemo) pero los das vuelta y te dice que encuentra primero crisantemo y despues almaDeDiamante.

https://github.com/NSci/PdP-TP-Objetos/blob/2f72c476281e0858ab54220bc507d8da432a1d46/TheBeagles/src/tests.wtest#L238

**Comment by gonziesc** [comment]
Holis!
Seguramente el problema es que el equals compara por identidad, y los sets son objectos distintos, por más de que tengan los mismos elementos. Se les ocurre alguna forma de probar el test sin validar la igualdad de los sets?

**Comment by NSci** [comment]
Por que son objetos distintos los sets ?
Otra forma seria probar la cantidad de elementos que tiene el set, o si el set contiene a almaDeDiamante y crisantemo, pero en ninguno de los dos casos te aseguras que el test este bien.
Podriamos hacer dos asserts con los dos casos que mencione, y ahi si nos asegurariamos que el test este bien pero no esta bien hacer dos asserts por test, si te falla no sabes cual es.
