### ISSUE TITLE
Correcciones Entrega 1

### ISSUE THREAD

**Issue by NSci** [NSci/PdP-TP-Objetos#4]
Ya están las correcciones resueltas @gonziesc

**Comment by gonziesc** [comment]
Revisadas. Está muy bien chicos, pero les dejo un comentario para pensar (no hace falta que hagan el cambio). Fijense que ustedes hacen en cantaEnGrupo `habilidad = 25` y en el otro metodo le setean 20. A mi en particular no me gustan esta clase de métodos que generan un efecto medio silencioso, ya que no hacen nada más.
En particular yo prefiero hacer cosas tipo `cantaEnGrupo() return habilidad + 5` y así no toco el estado del objeto. Este es un concepto bien de funcional y se llama transparencia referencial o inmutabilidad. Sirve muchísimo para detectar inconsistencias cuando hay problemas, ya que sabes que no hay métodos que estén tocando algo sin que uno lo vea.

**Comment by NSci** [comment]
Claro pero los metodos cantaEnGrupo() y dejaElGrupo() no retornan la habilidad, simplemente la modifican. Me parece que estaria mal poner en un metodo llamado cantaEnGrupo()  un : return habilidad + 5, ya que no tendria sentido que devuelva la habilidad cuando le estamos diciendo que cante en grupo, por eso es que hicimos esos dos setters.

**Comment by gonziesc** [comment]
Ojo, no hicieron dos setters, si no que esos métodos cambian el estado del objeto, que no es lo mismo. Claramente con su diseño actual no podrían retornar `habilidad + 5` porque además perderían el polimorfismo cuando piden la habilidad, deberian mandar los mensajes cantaEnGrupo o cantaSolo y saber de antemano como va a cantar. Una solución a esto sería modelar la formaDeCantar con una interfaz. Ambos comprenden el método cantar() y retornan habilidad o habilidad + 5 dependiendo de si es el objeto Grupo o el objeto Solista.
Claramente esta solución es mucho más compleja que la que ustedes propusieron, es simplemente para que empiecen a ver otras soluciones que van a aparecer para problemas más complejos.
