### ISSUE TITLE
Entrega 2

### ISSUE THREAD

**Issue by SantiagoLujan** [NSci/PdP-TP-Objetos#5]

**Comment by NSci** [comment]
@gonziesc ya realizamos las correcciones, pero tenemos un problema con un test que no podemos solucionar, nos dice que lo esperado es distinto de lo encontrado cuando es lo mismo.

**Comment by gonziesc** [comment]
Hola ! Perdón que los colgué, estuve a full estos dias. A más tardar el lunes lo vemos, trato de mirarlo el finde.

**Comment by gonziesc** [comment]
Ahí revisé. Les subí dos issues cortitas (no sé si alguna ya es de la 3). Qué test no les anda y por qué? lo pudieron solucionar? Cualquier cosa lo podemos ver el Lunes también.
